version: '2'

services:
  new_bcnfstar:
    image: bcnfstar
    ports:
    - 80:80
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_TYPE=postgres
      - DB_PASSWORD=
      - REDIS_HOST=redis
    links:
      - redis

  redis:
    image: redis:latest