name: Generate Documentation

on:
  push:
    branches:    
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate documentation
      run: |
        npm run docs

    - name: Commit generated documentation
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto-generate documentation

